<a href="https://colab.research.google.com/github/316104127/IOT_Perceptron/blob/main/IOT_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Created on Fri Jun 2020
@author: Sidnei Alves de Araújo
Implementação do Perceptron conforme algoritmo dado em aula 
"""


import numpy as np

#passo 0
def le_conj_trein(text_arq):
    arq = open(text_arq, 'r')  #abre o arquivo
    linhas_arq = []  #declara uma matriz para receber as linhas do arquivo
    matriz = [] #declaro uma matriz para receber o conjunto de treinamento
    linhas_arq = arq.readlines() #quebra o arquivo em linhas e armazena em linhas_arq
    arq.close()  #fecha o arquivo
    for i in range(len(linhas_arq)):          
        matriz.append(linhas_arq[i].split())  #aqui separa os valores contidos em cada linha do arquivo 
    #converte os valores lidos em números e coloca no conj de treinamento
    ct = np.zeros( (len(matriz),len(matriz[0])),'float')
    #print(matriz)
    for i in range(ct.shape[0]):
        for j in range(ct.shape[1]):
            ct[i][j] = float(matriz[i][j])
    return ct # retorna uma a matriz no formato ndarray 

#passo 1    
def incializa_pesos(w):
    for i in range(len(w)):
        w[i] = np.random.uniform(-1, 1)
        
    return w

#passo 2    
def calc_s(x,w):
    s = 0
    for i in range(len(x)):
        s = s + x[i] * w[i]  
    return s

#passo 3    
def calc_y(s):
    if s>=0: return 1
    else: return -1

#passo 4    
def calc_erro(d,y):
    return d-y

#passo 5
def atualiza_pesos(wt, x, erro):
    wt1 = wt
    for i in range(len(wt)):
        wt1[i] = wt[i] + TX_AP * erro * x[i]
    return wt1

#Fazer predição para um padrão p
def predicao_rna(p):
    print("======")
    x = np.append([BIAS],p, axis=0)
    print(f"Predição de X{x}")
    s = calc_s(x,w)
    print(f"Predição de S{s}")
    y = calc_y(s)
    print(f"Predição de Y{y}")
    print("======")
    
    return y

#############################################  Passos da RNA Percepetron ######################
#lê o conjunto de treinamento (passo 0)
ct = le_conj_trein('Porta_OR.txt')
num_padroes = ct.shape[0]
num_atrib = ct.shape[1]-1  
print('Conjunto de Treinamento:')
print(ct)
#separa padroes (p) e saídas desejadas (d)
p = ct[:,0:num_atrib]
print(p)
d = ct[:,num_atrib]
print(d)

w = []
#Passo 1 do algoritmo
#Parametros da RNA
BIAS    = 1.0  #Fixa o valor de Bias
TX_AP   = 0.1  #Taxa de Aprendizagem
EPOCAS  = 10000
#cria e inicializa vetor de pesos
w = np.zeros((num_atrib+1),'float')

print("*******************************")
print("teste 1")
w = incializa_pesos(w)
#w = [0.5, 0.7, 0.9, 0.1]
cont = 1
print('Conjunto de pesos iniciais:')
print(w)

while(cont < EPOCAS):
    #print(f"ÉPOCA:{cont}--------")
    erro_tot = 0
    for i in range(num_padroes):
      
      x = np.append([BIAS],p[i], axis=0)
      #print(f"X: {x}")
      #Passo 2 do algoritmo - Para o padrão i Calcula S
      s = calc_s(x,w)
      #print(f"S: {s}")
      #Passo 3 do algoritmo - Calcula y
      y = calc_y(s)
      #print(f"Y: {y}")
      
      #Passo 4 do algoritmo - Calcula erro     
      erro = calc_erro(d[i], y)
      #print(f"ERRO: {erro}")
      
      #Passo 5 do algoritmo - Se erro <> zero, atualiza pesos
       
      if erro !=0:
          #print(w)  
          w = atualiza_pesos(w,x,erro)
          erro_tot = erro_tot + np.abs(erro)
    #verifica critério de parada
    if erro_tot == 0:
        break
    #incrementa contador de épocas
    cont=cont+1
    
    
    

print('Treinamento finalizado com', cont, 'Epocas')
print('Conjunto de pesos finais:')
print(w)    

# Predições teste
print("Predições teste")
padrao = [0.5,	0.7, 0.1] 
pred = predicao_rna(padrao)
print('Valor de saída para o padrao ', padrao, ' = ', pred)




print("*******************************")
print("teste 2")
w = incializa_pesos(w)
#w = [0.9, 0.2, 0.9, 0.4]
cont = 1
print('Conjunto de pesos iniciais:')
print(w)

while(cont < EPOCAS):
    #print(f"ÉPOCA:{cont}--------")
    erro_tot = 0
    for i in range(num_padroes):
      
      x = np.append([BIAS],p[i], axis=0)
      #print(f"X: {x}")
      #Passo 2 do algoritmo - Para o padrão i Calcula S
      s = calc_s(x,w)
      #print(f"S: {s}")
      #Passo 3 do algoritmo - Calcula y
      y = calc_y(s)
      #print(f"Y: {y}")
      
      #Passo 4 do algoritmo - Calcula erro     
      erro = calc_erro(d[i], y)
      #print(f"ERRO: {erro}")
      
      #Passo 5 do algoritmo - Se erro <> zero, atualiza pesos
       
      if erro !=0:
          #print(w)  
          w = atualiza_pesos(w,x,erro)
          erro_tot = erro_tot + np.abs(erro)
    #verifica critério de parada
    if erro_tot == 0:
        break
    #incrementa contador de épocas
    cont=cont+1
    
    
    

print('Treinamento finalizado com', cont, 'Epocas')
print('Conjunto de pesos finais:')
print(w)    

# Predições teste
print("Predições teste")
padrao = [0.6,	0.9, 0.8] 
pred = predicao_rna(padrao)
print('Valor de saída para o padrao ', padrao, ' = ', pred)



print("*******************************")
print("teste 3")
w = incializa_pesos(w)
cont = 1
print('Conjunto de pesos iniciais:')
print(w)

while(cont < EPOCAS):
    
    erro_tot = 0
    for i in range(num_padroes):
      
      x = np.append([BIAS],p[i], axis=0)
      
      #Passo 2 do algoritmo - Para o padrão i Calcula S
      s = calc_s(x,w)
      
      #Passo 3 do algoritmo - Calcula y
      y = calc_y(s)
      
      
      #Passo 4 do algoritmo - Calcula erro     
      erro = calc_erro(d[i], y)
      
      
      #Passo 5 do algoritmo - Se erro <> zero, atualiza pesos
       
      if erro !=0:
           
          w = atualiza_pesos(w,x,erro)
          erro_tot = erro_tot + np.abs(erro)
    #verifica critério de parada
    if erro_tot == 0:
        break
    #incrementa contador de épocas
    cont=cont+1
    
    
    

print('Treinamento finalizado com', cont, 'Epocas')
print('Conjunto de pesos finais:')
print(w)    

# Predições teste
print("Predições teste")
padrao = [0.3,	0.7, 0.2] 
pred = predicao_rna(padrao)
print('Valor de saída para o padrao ', padrao, ' = ', pred) 

Conjunto de Treinamento:
[[ 0.1  0.4  0.7  1. ]
 [ 0.5  0.7  0.1  1. ]
 [ 0.6  0.9  0.8 -1. ]
 [ 0.3  0.7  0.2 -1. ]]
[[0.1 0.4 0.7]
 [0.5 0.7 0.1]
 [0.6 0.9 0.8]
 [0.3 0.7 0.2]]
[ 1.  1. -1. -1.]
*******************************
teste 1
Conjunto de pesos iniciais:
[-0.6872369   0.66480712 -0.69234466 -0.52540248]
Treinamento finalizado com 9 Epocas
Conjunto de pesos finais:
[ 0.3127631   0.44480712 -0.63234466 -0.02540248]
Predições teste
Predição de X[1.  0.5 0.7 0.1]
Predição de S0.08998514871997874
Predição de Y1
Valor de saída para o padrao  [0.5, 0.7, 0.1]  =  1
*******************************
teste 2
Conjunto de pesos iniciais:
[-0.45817769 -0.54219452  0.79058623  0.78887103]
Treinamento finalizado com 112 Epocas
Conjunto de pesos finais:
[ 0.74182231  0.59780548 -1.38941377 -0.01112897]
Predições teste
Predição de X[1.  0.6 0.9 0.8]
Predição de S-0.1588699792800918
Predição de Y-1
Valor de saída para o padrao  [0.6, 0.9, 0.8]  =  -1
*******************************
teste 3
Conju

In [ ]:
"""
Resposta para atividade de Implementação de Perceptron
"""

import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split


def text():
    print("\n\n######################################\n\n")
    

#cria uma matriz e armazena nela o conjunto de treinamento
ct = np.array([[ 0.1,	0.4,	0.7,	1],
               [ 0.5,	0.7,	0.1,	1],
               [ 0.6,	0.9,	0.8,	-1],
               [ 0.3,	0.7,    0.2,	-1]])

#Separa as colunas do conjunto de treinamento em sintomas (s) e diagnóstico (d) 
p = ct[:,0:3]
print(p)
d = ct[:,3]
print(d)

X_train = p
y_train = d
X_test = p
y_test = d



#Cria a RNA do tipo Multi-layer Perceptron com a configuração indicada
clf = MLPClassifier(hidden_layer_sizes=(10,), learning_rate='constant', 
                    learning_rate_init=0.005, max_iter=3000)

#Treina a RNA
clf.fit(X_train, y_train)

#Calcula e imprime a acurácia do treinamento
acuracia_trein = clf.score(X_test, y_test)
print("Acurácia do Treinamento = %.2f%%" %(acuracia_trein*100.0))

#cria uma matriz com os sintomas dos novos casos 
Novos_Registros = np.array([[0.1, 0.7, 0.3],
                           [0.4, 0.2, 0.6],
                            [0.1, 0.5, 0.6],
                            [0.7, 0.3, 0.4]])

text()

print("Primeiro Conjunto")
print(Novos_Registros)



#Faz a predição para os novos casos e armazena no vetor de respostas (resp)
resp = clf.predict(Novos_Registros)
print(f"Resposta {resp}")


#Exibe os resultados da RNA MLP para os novos casos 
print("\nPredição da RNA para R1")

if resp[0] == 1: print("Tangerina")
elif resp[0] == -1: print("laranja")
    
print("\nPredição da RNA para R2")
if resp[1] == 1: print("Tangerina")
elif resp[1] == -1: print("laranja")

print("\nPredição da RNA para R3")
if resp[2] == 1: print("Tangerina")
elif resp[2] == -1: print("laranja")

print("\nPredição da RNA para R4")
if resp[3] == 1: print("Tangerina")
elif resp[3] == -1: print("laranja")




text()
Novos_Registros = np.array([[0.7, 0.3, 0.4],
                           [0.2, 0.1, 0.6],
                            [0.3, 0.6, 0.1],
                            [0.5, 0.1, 0.8]])

print("Segundo Conjunto")
print(Novos_Registros)
resp = clf.predict(Novos_Registros)
print(f"Resposta {resp}")

print("\nPredição da RNA para R1")
if resp[0] == 1: print("Tangerina")
elif resp[0] == -1: print("laranja")
    
print("\nPredição da RNA para R2")
if resp[1] == 1: print("Tangerina")
elif resp[1] == -1: print("laranja")

print("\nPredição da RNA para R3")
if resp[2] == 1: print("Tangerina")
elif resp[2] == -1: print("laranja")

print("\nPredição da RNA para R4")
if resp[3] == 1: print("Tangerina")
elif resp[3] == -1: print("laranja")

text()

Novos_Registros = np.array([[0.6, 0.9, 0.2],
                           [0.9, 0.8, 0.1],
                            [0.2, 0.7, 0.5],
                            [0.8, 0.1, 0.4]])

print("Terceiro Conjunto")
print(Novos_Registros)
resp = clf.predict(Novos_Registros)
print(f"Resposta {resp}")

print("\nPredição da RNA para R1")
if resp[0] == 1: print("Tangerina")
elif resp[0] == -1: print("laranja")
    
print("\nPredição da RNA para R2")
if resp[1] == 1: print("Tangerina")
elif resp[1] == -1: print("laranja")

print("\nPredição da RNA para R3")
if resp[2] == 1: print("Tangerina")
elif resp[2] == -1: print("laranja")

print("\nPredição da RNA para R4")
if resp[3] == 1: print("Tangerina")
elif resp[3] == -1: print("laranja")

[[0.1 0.4 0.7]
 [0.5 0.7 0.1]
 [0.6 0.9 0.8]
 [0.3 0.7 0.2]]
[ 1.  1. -1. -1.]
Acurácia do Treinamento = 100.00%


######################################


Primeiro Conjunto
[[0.1 0.7 0.3]
 [0.4 0.2 0.6]
 [0.1 0.5 0.6]
 [0.7 0.3 0.4]]
Resposta [-1.  1.  1.  1.]

Predição da RNA para R1
laranja

Predição da RNA para R2
Tangerina

Predição da RNA para R3
Tangerina

Predição da RNA para R4
Tangerina


######################################


Segundo Conjunto
[[0.7 0.3 0.4]
 [0.2 0.1 0.6]
 [0.3 0.6 0.1]
 [0.5 0.1 0.8]]
Resposta [1. 1. 1. 1.]

Predição da RNA para R1
Tangerina

Predição da RNA para R2
Tangerina

Predição da RNA para R3
Tangerina

Predição da RNA para R4
Tangerina


######################################


Terceiro Conjunto
[[0.6 0.9 0.2]
 [0.9 0.8 0.1]
 [0.2 0.7 0.5]
 [0.8 0.1 0.4]]
Resposta [-1.  1. -1.  1.]

Predição da RNA para R1
laranja

Predição da RNA para R2
Tangerina

Predição da RNA para R3
laranja

Predição da RNA para R4
Tangerina
